vendedores = `[{
    "id": 1,
    "nombre": "Rochelle",
    "apellidos": "Dennistoun",
    "email": "rdennistoun0@gravatar.com",
    "telefono": "689-464-9493"
}, {
    "id": 2,
    "nombre": "Barbra",
    "apellidos": "Foye",
    "email": "bfoye1@unicef.org",
    "telefono": "211-488-9256"
}, {
    "id": 3,
    "nombre": "Fay",
    "apellidos": "McCree",
    "email": "fmccree2@geocities.jp",
    "telefono": "855-590-3921"
}, {
    "id": 4,
    "nombre": "Ina",
    "apellidos": "Vittel",
    "email": "ivittel3@storify.com",
    "telefono": "158-515-0746"
}, {
    "id": 5,
    "nombre": "Marilee",
    "apellidos": "Goult",
    "email": "mgoult4@creativecommons.org",
    "telefono": "642-818-7816"
}, {
    "id": 6,
    "nombre": "Udell",
    "apellidos": "Bradforth",
    "email": "ubradforth5@google.fr",
    "telefono": "602-852-4100"
}, {
    "id": 7,
    "nombre": "Krystalle",
    "apellidos": "Limbrick",
    "email": "klimbrick6@tiny.cc",
    "telefono": "412-205-4063"
}, {
    "id": 8,
    "nombre": "Nickie",
    "apellidos": "Erlam",
    "email": "nerlam7@sun.com",
    "telefono": "448-374-7564"
}, {
    "id": 9,
    "nombre": "Missie",
    "apellidos": "Curle",
    "email": "mcurle8@netscape.com",
    "telefono": "416-597-1499"
}, {
    "id": 10,
    "nombre": "Cordelie",
    "apellidos": "Etienne",
    "email": "cetienne9@fc2.com",
    "telefono": "574-530-1589"
}]
`;